### ISSUE TITLE
Roadmap for v0.1.9

### ISSUE THREAD

**Issue by enmerk4r** [enmerk4r/Swiftlet#18]
## New components:
- [x] URLencode
- [x] Hex to RGB
- [x] RGB to Hex
- [x] Byte Array to Bitmap
- [x] Bitmap to Byte Array
- [x] Bitmap to Mesh
- [x] QR code generator 
- [x] Throttle (Sleep)
- [x] Deconstruct Headers
- [x] Deconstruct Query Params
- [x] GUID generator
- [x] Base64 encode for byte arrays
- [x] Base64 decode for byte arrays
- [x] Create MultipartForm Body Named
- [x] Create MultipartForm Body Unnamed

## Fixes:
- [x] Make sure ```Content-Type``` header from Body is propagated to the Request Headers #20 
- [x] Make sure exceptions are actually thrown (get rid of the obscure "One or more errors occurred" message)
- [x] Figure out why Swiftlet freaks out when on VPN
- [x] Check what happens when multithreading is turned off
