### ISSUE TITLE
Swiftlet 0.2.0 roadmap

### ISSUE THREAD

**Issue by enmerk4r** [enmerk4r/Swiftlet#22]
- [ ] Migration to .Net 7 for compatibility with Rhino 8
- [ ] Improve Bitmaps casting for compatibility with ShapeDiver bitmaps
- [ ] Add an option to request components to skip certificate verification in case of using self-signed SSL's
